name: calendar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.2
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  flutter_colorpicker: ^1.1.0
  flutter_color: ^2.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: fonts/NotoSansJP-Regular.ttf
          weight: 300
        - asset: fonts/NotoSansJP-Bold.ttf
          weight: 300